version: '3.8'

services:
  app:
    image: your-dockerhub-username/your-image-name:${{ github.sha }}
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://your-mysql-server-ip:3306/gymapp?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=watafaking
      - SPRING_DATASOURCE_PASSWORD=amogusas
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL-AUTO=create-drop