name: Deploy to Server
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SECRET_KEY }}

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy code
        run: |
          sshpass -p "${{ secrets.SERVER_KEY }}" scp -o StrictHostKeyChecking=no -P ${{ secrets.SERVER_PORT }} target/${{ secrets.JAR_FILE_NAME }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/root/gymproject
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} 'cd /root/gymproject && java -jar ${{ secrets.JAR_FILE_NAME }}'
