name: Delete Failed Workflows
on:
  workflow_dispatch:
  
jobs:
  delete-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Get Failed Workflows
        id: failed-workflows
        run: |
          echo "::set-output name=failed_workflows::$(gh run list -f '{{.ID}}' -s completed -s failure)"
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Failed Workflows
        if: steps.failed-workflows.outputs.failed_workflows != ''
        run: |
          for id in ${failed-workflows};
          do
            echo "Deleting workflow ${id}..."
            gh workflow run ${id} delete -y
          done
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
