name: Run Jar on Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Add VPS host key to known_hosts
      run: |
        ssh-keyscan -H 45.9.191.191 >> ~/.ssh/known_hosts

    - name: Deploy to VPS
      run: |
        set -e
        scp Dockerfile GymProject.jar root@45.9.191.191:/root/GymProject
        ssh root@45.9.191.191 'docker stop gymproject-container || true'
        ssh root@45.9.191.191 'docker rm gymproject-container || true'
        ssh root@45.9.191.191 'docker build -t gymproject /root/GymProject'
        ssh root@45.9.191.191 'docker run --name gymproject-container -d gymproject || (docker logs gymproject-container && false)'
