name: Deploy to VPS

on:
  push:
    branches: [main]

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_KEY: ${{ secrets.SERVER_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR file
        run: |
          curl -LJO https://github.com/ArturasBidva/GymProject/raw/main/GymProject.jar
          sudo mv GymProject.jar /root/GymProject

      - name: Set ownership of GymProject directory
        run: sudo chown -R root:root '/root/GymProject'

      - name: Kill Running GymProject Docker Containers
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} -p ${{ env.SERVER_PORT }} 'docker ps -a --filter "label=gymproject" -q | xargs -r docker kill'

      - name: Run Docker Compose
        run: ssh -o StrictHostKeyChecking=no ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }} -p ${{ env.SERVER_PORT }} 'cd /root/GymProject && docker-compose up -d'
        env:
          DOCKER_COMPOSE_PROJECT_NAME: gymproject
        shell: bash