name: Deploy to VPS

on:
  push:
    branches: [main]

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_KEY: ${{ secrets.SERVER_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Download JAR file
        uses: actions/download-artifact@v2
        with:
          name: GymProject
          path: /root/GymProject/GymProject.jar

      - name: Set ownership of GymProject directory
        run: sudo chown -R root:root '/root/GymProject'

      - name: Kill Running Docker Containers
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} 'docker kill $(docker ps -q)'

      - name: Run Docker Compose
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} 'cd /root/GymProject && docker-compose up -d'