name: Deploy to VPS

on:
  push:
    branches: [main]

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_KEY: ${{ secrets.SERVER_KEY }}
  JAVA_HOME: /opt/hostedtoolcache/Java_Adopt_jdk/17.0.6-10/x64

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          java-home: ${{ env.JAVA_HOME }}
      
      - name: Make pom.xml readable
        run: sudo cd /root/GymProject && sudo chmod +r pom.xml
              
          
      - name: Build Jar File
        run: mvn -B package --file /root/GymProject/pom.xml
        
      - name: Copy jar file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.SERVER_HOST }}
          username: ${{ env.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ env.SERVER_PORT }}
          source: "GymProject/target/my-app.jar"
          target: "/root/GymProject/"
          
      - name: Kill Running Docker Containers
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} 'docker kill $(docker ps -q)'
        
      - name: Run Docker Compose
        run: ssh -o StrictHostKeyChecking=no root@${{ secrets.SERVER_HOST }} 'cd /root/GymProject && docker-compose up -d'
