name: Run Jar on Docker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Deploy to VPS
      run: |
        scp Dockerfile GymProject.jar root@your-vps-ip:/root/GymProject
        ssh root@your-vps-ip 'docker build -t gymproject /root/GymProject'
        ssh root@your-vps-ip 'docker run --name gymproject-container -d gymproject'