name: Docker Build and Run

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        tags: your-image-name:latest

    - name: Run Docker Container
      uses: docker/compose-action@v1
      with:
        compose-file: docker-compose.yml
        service: your-service-name
        command: java -jar /app.jar
        env: |
          SPRING_PROFILES_ACTIVE=prod
          SPRING_DATASOURCE_URL=jdbc:jdbc:mysql://gym-db:3306/gymapp?useSSL=false
          SPRING_DATASOURCE_USERNAME=watafaking
          SPRING_DATASOURCE_PASSWORD=amogusas
